/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sepatusport;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author User
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private DefaultTableModel tableModel;
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    public App() {
        initComponents();
        setLocationRelativeTo(null);
        cbUkuran.setSelectedIndex(-1);
        tableModel = new DefaultTableModel(new Object[]{"ID", "Merek", "Tipe", "Model", "Warna", "Ukuran", "Harga(Rp)"}, 0);
        tblSepatu.setModel(tableModel);
        tblSepatu.getTableHeader().setFont(new Font("Microsoft Sans Serif", Font.BOLD, 12));
        tblSepatu.getTableHeader().setForeground(new Color(238, 238, 238));
        tblSepatu.getTableHeader().setBackground(new Color(0, 173, 181));
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        tblSepatu.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblSepatu.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblSepatu.getColumnModel().getColumn(1).setPreferredWidth(70);
        tblSepatu.getColumnModel().getColumn(2).setPreferredWidth(125);
        tblSepatu.getColumnModel().getColumn(3).setPreferredWidth(70);
        tblSepatu.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblSepatu.getColumnModel().getColumn(5).setPreferredWidth(50);
        tblSepatu.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        updateTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        txtMerek = new javax.swing.JTextField();
        cbUkuran = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSepatu = new javax.swing.JTable();
        txtTipe = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sepatu Sport");

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        btnLogout.setBackground(new java.awt.Color(0, 173, 181));
        btnLogout.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(238, 238, 238));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtMerek.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        cbUkuran.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50" }));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        tblSepatu.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tblSepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSepatu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSepatuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSepatu);

        txtTipe.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        txtId.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        txtHarga.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        txtWarna.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel2.setText("Model");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setText("Tipe");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setText("Ukuran");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setText("Merek");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel6.setText("Warna");

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel7.setText("Harga(Rp)");

        btnHapus.setBackground(new java.awt.Color(0, 173, 181));
        btnHapus.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(238, 238, 238));
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 173, 181));
        btnUpdate.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(238, 238, 238));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 173, 181));
        btnAdd.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(238, 238, 238));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));

        jRadioButton1.setBackground(new java.awt.Color(57, 62, 70));
        jRadioButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(238, 238, 238));
        jRadioButton1.setText("Pria");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(57, 62, 70));
        jRadioButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(238, 238, 238));
        jRadioButton2.setText("Wanita");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        txtSearch.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 173, 181));
        btnSearch.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(238, 238, 238));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 62, 70));
        jLabel8.setText("Sepatu Sport");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sepatusport/random sepatu.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(57, 62, 70));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        btnClear.setBackground(new java.awt.Color(0, 173, 181));
        btnClear.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btnClear.setForeground(new java.awt.Color(238, 238, 238));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSearch)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void clear() {
        txtId.setText("");
        txtMerek.setText("");
        txtTipe.setText("");
        txtWarna.setText("");
        cbUkuran.setSelectedIndex(-1);
        txtHarga.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
    }
    
    private boolean cekDataKosong(){
        if (txtMerek.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Merek Masih Kosong !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtMerek.requestFocus();
            return false;
        } else if (txtTipe.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tipe Masih Kosong !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtTipe.requestFocus();
            return false;
        } else if (cbUkuran.getSelectedItem() == null || cbUkuran.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Ukuran Belum Dipilih !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            cbUkuran.requestFocus();
            return false;
        } else if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(null, "Data Model Belum Dipilih !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data ID Masih Kosong !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtId.requestFocus();
            return false;
        } else if (txtWarna.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Warna Masih Kosong !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtWarna.requestFocus();
            return false;
        } else if (txtHarga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Harga Masih Kosong !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtHarga.requestFocus();
            return false;
        }
        return true;
    }
    
    //Refresh Tabel
    private void updateTableData() {
        try {
            // Menghapus semua baris data sebelum melakukan refresh
            tableModel.setRowCount(0);

            Connection connection = dbConnection.getConnection();
            Statement statement = connection.createStatement();
            String query = "SELECT * FROM sepatu";
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String merek = resultSet.getString("merek");
                String tipe = resultSet.getString("tipe");
                String model = resultSet.getString("model");
                String warna = resultSet.getString("warna");
                int ukuran = resultSet.getInt("ukuran");
                int harga = resultSet.getInt("harga");

                // Menambahkan data ke dalam DefaultTableModel
                tableModel.addRow(new Object[]{id, merek, tipe, model, warna, ukuran, harga});
            }

            resultSet.close();
            statement.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    //Logout
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login form1 = new Login();
        form1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    //Add sepatu
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (cekDataKosong()) {    
            String id = txtId.getText();
            String merek = txtMerek.getText();
            String tipe = txtTipe.getText();
            String warna = txtWarna.getText();
            //String ukuran = cbUkuran.getText();
            String ukuran = cbUkuran.getSelectedItem().toString();
            Integer ukuranInteger = Integer.valueOf(ukuran);
            String selectedValue;
            if (jRadioButton1.isSelected()) {
                selectedValue = "Pria";
            } else if (jRadioButton2.isSelected()) {
                selectedValue = "Wanita";
            } else {
                selectedValue = "Default Value";
            }
            String model = selectedValue;

            String harga = txtHarga.getText();

            Integer hargaInteger = Integer.valueOf(harga);
            sepatu sepatu = new sepatu(id, merek, tipe, model, warna, ukuranInteger, hargaInteger);

            //sepatu.saveToDatabase();
            
            if (sepatu.isSepatuExists(id)) {
                JOptionPane.showMessageDialog(this,"ID Sepatu Sudah Ada !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            } else {
                sepatu.saveToDatabase();
                updateTableData();
                JOptionPane.showMessageDialog(this,"Sepatu Berhasil Ditambahkan", "Information", JOptionPane.INFORMATION_MESSAGE);
                clear();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    //Hapus
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = tblSepatu.getSelectedRow();
        if (selectedRow != -1) {
            // Dapatkan data yang dipilih
            String id = (String) tblSepatu.getValueAt(selectedRow, 0);
            String merek = (String) tblSepatu.getValueAt(selectedRow, 1);
            String tipe = (String) tblSepatu.getValueAt(selectedRow, 2);
            String model = (String) tblSepatu.getValueAt(selectedRow, 3);
            String warna = (String) tblSepatu.getValueAt(selectedRow, 4);
            int ukuranInteger = (int) tblSepatu.getValueAt(selectedRow, 5);
            int hargaInteger = (int) tblSepatu.getValueAt(selectedRow, 6);
            // Tampilkan dialog konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                
                sepatu sepatu = new sepatu(id, merek, tipe, model, warna, ukuranInteger, hargaInteger);
                // Hapus data dari database
                sepatu.deleteFromDatabase(id);
                updateTableData();
                clear();
                JOptionPane.showMessageDialog(this,"Sepatu Berhasil Dihapus", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silakan pilih data yang ingin dihapus", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed
    
    //Pilih pria, wanita ga kepilih
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    //Pilih wanita, pria ga kepilih
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    //Update
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (cekDataKosong()) {
            int selectedRow = tblSepatu.getSelectedRow();
            if (selectedRow != -1) {
                String id = txtId.getText();
                String merek = txtMerek.getText();
                String tipe = txtTipe.getText();
                String warna = txtWarna.getText();
                //String ukuran = cbUkuran.getText();
                String ukuran = cbUkuran.getSelectedItem().toString();
                Integer ukuranInteger = Integer.valueOf(ukuran);
                String selectedValue;
                if (jRadioButton1.isSelected()) {
                    selectedValue = "Pria";
                } else if (jRadioButton2.isSelected()) {
                    selectedValue = "Wanita";
                } else {
                    selectedValue = "Default Value";
                }
                String model = selectedValue;

                String harga = txtHarga.getText();

                Integer hargaInteger = Integer.valueOf(harga);
                // Tampilkan dialog konfirmasi penghapusan
                int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengupdate data ini?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    sepatu sepatu = new sepatu(id, merek, tipe, model, warna, ukuranInteger, hargaInteger);
                    try {
                        // Hapus data dari database
                        sepatu.updateInDatabase();
                        updateTableData();
                        JOptionPane.showMessageDialog(this,"Sepatu Berhasil DiUpdate", "Information", JOptionPane.INFORMATION_MESSAGE);
                        clear();
                    } catch (RuntimeException e) {
                        JOptionPane.showMessageDialog(null, "ID Tidak Ditemukan !!!", "WARNING", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Silakan pilih data yang ingin diupdate", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    //Mengambil data dari tabel untuk di tampilkan di textfield, Combobox, dan Radio Button yang ada
    private void tblSepatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSepatuMouseClicked
        int selectedRow = tblSepatu.getSelectedRow();
        if (selectedRow != -1) {
            // Dapatkan data yang dipilih
            String id = tblSepatu.getValueAt(selectedRow, 0).toString();
            String merek = tblSepatu.getValueAt(selectedRow, 1).toString();
            String tipe = tblSepatu.getValueAt(selectedRow, 2).toString();
            String model = tblSepatu.getValueAt(selectedRow, 3).toString();
            String warna = tblSepatu.getValueAt(selectedRow, 4).toString();
            String ukuran = tblSepatu.getValueAt(selectedRow, 5).toString();
            String harga = tblSepatu.getValueAt(selectedRow, 6).toString();
            
            txtId.setText(id);
            txtMerek.setText(merek);
            txtTipe.setText(tipe);
            if (model.equalsIgnoreCase("Pria")) {
                jRadioButton1.setSelected(true);
                jRadioButton2.setSelected(false);
            } else if (model.equalsIgnoreCase("Wanita")) {
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(true);
            }
            txtWarna.setText(warna);
            cbUkuran.setSelectedItem(ukuran);
            txtHarga.setText(harga);
        }
    }//GEN-LAST:event_tblSepatuMouseClicked
    
    //Methode Searching
    public List<sepatu> searchFromDatabase(String keyword) {
        List<sepatu> results = new ArrayList<>();

        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            // Mengambil koneksi dari dbConnection
            connection = dbConnection.getConnection();

            // Membuat statement SQL dengan parameter
            String query = "SELECT * FROM sepatu WHERE id LIKE ? OR tipe LIKE ? OR merek LIKE ? OR model LIKE ? OR warna LIKE ?";
            statement = connection.prepareStatement(query);
            statement.setString(1, "%" + keyword + "%");
            statement.setString(2, "%" + keyword + "%");
            statement.setString(3, "%" + keyword + "%");
            statement.setString(4, "%" + keyword + "%");
            statement.setString(5, "%" + keyword + "%");

            // Menjalankan pernyataan SQL
            resultSet = statement.executeQuery();

            // Mengambil hasil pencarian dan menambahkannya ke dalam daftar hasil
            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String merek = resultSet.getString("merek");
                String tipe = resultSet.getString("tipe");
                String model = resultSet.getString("model");
                String warna = resultSet.getString("warna");
                int ukuran = resultSet.getInt("ukuran");
                int harga = resultSet.getInt("harga");

                sepatu data = new sepatu(id, merek, tipe, model, warna, ukuran, harga);
                results.add(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Menutup statement, result set, dan koneksi
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (statement != null) {
                    statement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return results;
    }
    
    //Button untuk searching
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText();
        
        List<sepatu> searchResults = searchFromDatabase(keyword);

        // Hapus data yang ada di tabel
        DefaultTableModel model = (DefaultTableModel) tblSepatu.getModel();
        model.setRowCount(0);

        // Tambahkan hasil pencarian ke dalam tabel
        for (sepatu data : searchResults) {
            Object[] row = {data.getId(), data.getMerek(), data.getTipe(), data.getModel(), data.getWarna(), data.getUkuran(), data.getHarga()};
            model.addRow(row);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    
    //Supaya Inputan di txtHarga hanya bisa angka
    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtHargaKeyTyped
    
    //Keypress Enter Searching
    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnSearchActionPerformed(null);
            
            String keyword = txtSearch.getText();
    
            List<sepatu> searchResults = searchFromDatabase(keyword);

            // Hapus data yang ada di tabel
            DefaultTableModel model = (DefaultTableModel) tblSepatu.getModel();
            model.setRowCount(0);

            // Tambahkan hasil pencarian ke dalam tabel
            for (sepatu data : searchResults) {
                Object[] row = {data.getId(), data.getMerek(), data.getTipe(), data.getModel(), data.getWarna(), data.getUkuran(), data.getHarga()};
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed
    
    //Button Untuk Clear
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
        tblSepatu.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSepatu;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTipe;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
